version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=sujith
      - POSTGRES_PASSWORD=sujith
      - POSTGRES_DB=quiz_master
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: