
flyway:
    baselineOnMigrate: true
    schema: quiz_master
    user: sujith
    validate-on-migrate: false
server:
    port: 8080
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        username: sujith
        password: sujith
        url: jdbc:postgresql://192.168.99.100:5433/quiz_master?sslfactory=org.postgresql.ssl.NonValidatingFactory
        type: com.zaxxer.hikari.HikariDataSource
        initialization-mode: always
        initialize: true
        hikari:
            maximum-pool-size: 100
            minimum-idle: 5
            max-lifetime: 60000
            idle-timeout: 1000
            auto-commit: true
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate.ddl-auto: none
        properties:
            hibernate:
                temp.use_jdbc_metadata_defaults: false
                default_schema: quiz_master
                format_sql: true
